"""Emit multi-board KiCad projects: pcb_ccs_sense + pcb_axis_octal.

GENERATED trees — do not hand-edit; regenerate via:
  uv run python -m generators.cli --board ccs|axis
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from generators.abi import SENSE_NETS
from generators.board_abi import (
    AXIS_STEER_PIN_COUNT,
    BUS_PINS,
    CCS_TRIM_REFS,
    PICO_PCB_PINS,
    PICO_PINS,
    PLANE_AB_PINS,
    PLANE_SENSE_PINS,
    PLANE_SENSE_PCB_PINS,
    axis_steer_pins,
)
from generators.emit_kicad import (
    KICAD_ROOT,
    _global_label,
    _lib_diode,
    _lib_r,
    _no_connect,
    _place_diode,
    _place_r,
    _sheet_base,
    _text,
    _wire,
)
from generators.mce_array import build_fabric
from generators.sexpr import det_uuid, write_sexpr

BANNER_BOARD = (
    "GENERATED by generators/ — do not hand-edit; "
    "uv run python -m generators.cli --board {board}"
)


def _emit_pro(out_dir: Path, name: str, root_sheet: str) -> None:
    root_uuid = det_uuid(f"sheet/{root_sheet}")
    pro = {
        "board": {
            "design_settings": {
                "defaults": {},
                "diff_pair_dimensions": [],
                "drc_exclusions": [],
                "rules": {},
                "track_widths": [],
                "via_dimensions": [],
            }
        },
        "boards": [],
        "libraries": {"pinned_footprint_libs": [], "pinned_symbol_libs": []},
        "meta": {"filename": f"{name}.kicad_pro", "version": 3},
        "net_settings": {"classes": [], "meta": {"version": 0}},
        "schematic": {
            "meta": {"version": 1},
            "page_layout_descr_file": "",
            "plot_directory": "",
        },
        "sheets": [[root_uuid, "Root"]],
        "text_variables": {},
    }
    (out_dir / f"{name}.kicad_pro").write_text(
        json.dumps(pro, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _root_port(name: str, x: float, y: float, sheet_uuid: str) -> list[list]:
    """Global-label connector stub on a root sheet (ERC-clean; no hierarchical parent)."""
    rx = x + 12.7
    ref = "Rt_" + re.sub(r"[^A-Za-z0-9]", "_", f"{name}_{x:g}_{y:g}")
    return [
        _global_label(name, x, y, 0),
        _wire(f"port/{name}@{x},{y}", x, y, rx, y),
        _wire(f"portv/{name}@{x},{y}", rx, y, rx, y + 3.81),
        _place_r(f"portR/{name}@{x},{y}", ref, "DNP_10k", rx, y, sheet_uuid),
        _no_connect(f"portRnc/{name}@{x},{y}", rx, y - 3.81),
    ]


def _connector_ports(
    items: list,
    suuid: str,
    prefix: str,
    pins: tuple[str, ...] | list[str],
    x0: float,
    y0: float,
) -> None:
    del prefix  # reserved for future silkscreen grouping
    y = y0
    x = x0
    for pin in pins:
        items.extend(_root_port(pin, x, y, suuid))
        y += 2.54
        if y > 180:
            y = y0
            x += 40.0


# --- Schematics -------------------------------------------------------------


def emit_ccs_sense_sch(out_dir: Path) -> Path:
    key = "ccs_sense"
    body, suuid = _sheet_base(
        key,
        "pcb_ccs_sense — CCS×3 + sense/fold + Pico + bus host",
        8,
        [_lib_r()],
    )
    items: list = [
        _text(f"{key}/banner", BANNER_BOARD.format(board="ccs"), 10, 8),
        _text(
            f"{key}/tune",
            "Tune: RTRIM_X/Y/INH (3296W), VDRIVE, JP_INH_POL — design_choices",
            10,
            13,
        ),
        _text(f"{key}/fold", "YA66 ≡ YB65 ≡ SENSE_FOLD (local fold)", 10, 18),
    ]

    # Three CCS trimpot stubs (pin1 wiper label, pin2 AGND).
    tx, ty = 180.0, 30.0
    for ref in CCS_TRIM_REFS:
        items.append(_place_r(f"{key}/{ref}", ref, "3296W", tx, ty, suuid))
        items.append(_global_label(f"{ref}_WIPER", tx, ty - 3.81, 90))
        items.append(_global_label("AGND", tx, ty + 3.81, 270))
        tx += 25.0

    items.append(_place_r(f"{key}/Rfold", "Rfold", "10k", 180, 70, suuid))
    items.append(_global_label("SENSE_FOLD", 180, 70 - 3.81, 90))
    items.append(_global_label("AGND", 180, 70 + 3.81, 270))

    # Connector pin stubs (root sheet → global labels, not hierarchical).
    _connector_ports(items, suuid, "sense", PLANE_SENSE_PINS, 20.0, 30.0)
    _connector_ports(items, suuid, "bus", BUS_PINS, 20.0, 55.0)
    _connector_ports(items, suuid, "pico", PICO_PINS, 70.0, 30.0)

    # CCS return sense resistors: CCS_* ↔ AGND (1 Ω).
    for name, y in (("CCS_X", 100.0), ("CCS_Y", 110.0), ("CCS_INH", 120.0)):
        items.append(_place_r(f"{key}/{name}", f"R_{name}", "1", 210.0, y, suuid))
        items.append(_global_label(name, 210.0, y - 3.81, 90))
        items.append(_global_label("AGND", 210.0, y + 3.81, 270))

    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    path = out_dir / f"{key}.kicad_sch"
    write_sexpr(path, body)
    return path


def emit_axis_octal_sch(out_dir: Path, group: int = 0) -> Path:
    fabric = build_fabric(64)
    tile = next(t for t in fabric.tiles if t.axis == "X" and t.group == group)

    key = "axis_octal"
    body, suuid = _sheet_base(
        key,
        f"pcb_axis_octal — decode+DMOS+SS14 group g={group} (X/Y identical PCB)",
        8,
        [_lib_diode(), _lib_r()],
    )
    items: list = [
        _text(f"{key}/banner", BANNER_BOARD.format(board="axis"), 10, 8),
        _text(
            f"{key}/id",
            "JP_AXIS=X|Y  JP_G[2:0]=group  bring-up: g=0",
            10,
            13,
        ),
        _text(
            f"{key}/pins",
            f"REQ-HIER-OCTAL steer pins={AXIS_STEER_PIN_COUNT} lines={list(tile.lines)}",
            10,
            18,
        ),
        _text(
            f"{key}/mpn",
            "Decode 74AHC138+74AHC238; DMOS TBD62783/TBD62083; steer SS14",
            10,
            23,
        ),
    ]

    steer_pins = axis_steer_pins(group)
    assert len(steer_pins) == AXIS_STEER_PIN_COUNT
    _connector_ports(items, suuid, "steer", list(steer_pins), 20.0, 35.0)
    _connector_ports(items, suuid, "bus", BUS_PINS, 100.0, 35.0)
    _connector_ports(items, suuid, "plane", PLANE_AB_PINS, 180.0, 35.0)

    # SS14 diodes for this group's diode law (from fabric tile).
    dx, dy = 260.0, 35.0
    for i, edge in enumerate(tile.diodes):
        ref = f"D{group}_{i}"
        items.append(_place_diode(f"{key}/{ref}", ref, dx, dy, suuid))
        items.append(_global_label(edge.anode, dx + 5.08, dy, 0))
        items.append(_global_label(edge.cathode, dx - 5.08, dy, 180))
        items.append(_wire(f"{key}/{ref}/a", dx + 3.81, dy, dx + 5.08, dy))
        items.append(_wire(f"{key}/{ref}/k", dx - 3.81, dy, dx - 5.08, dy))
        dy += 7.62
        if dy > 180:
            dy = 35.0
            dx += 35.0

    # Fail-safe pull resistors on enables.
    items.append(_place_r(f"{key}/Rpu_fwd", "Rpu_FWD", "10k", 100, 150, suuid))
    items.append(_global_label("FWD_EN_n", 100, 150 - 3.81, 90))
    items.append(_global_label("+3V3", 100, 150 + 3.81, 270))
    items.append(_place_r(f"{key}/Rpu_rev", "Rpu_REV", "10k", 120, 150, suuid))
    items.append(_global_label("REV_EN_n", 120, 150 - 3.81, 90))
    items.append(_global_label("+3V3", 120, 150 + 3.81, 270))
    items.append(_place_r(f"{key}/Rpd_dec", "Rpd_DEC", "10k", 140, 150, suuid))
    items.append(_global_label("DEC_EN", 140, 150 - 3.81, 90))
    items.append(_global_label("AGND", 140, 150 + 3.81, 270))

    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    path = out_dir / f"{key}.kicad_sch"
    write_sexpr(path, body)
    return path


# --- PCB layouts ------------------------------------------------------------

KICAD_PCB_VERSION = 20241229


def _pcb_layers_2() -> list:
    return [
        "layers",
        [0, "F.Cu", "signal"],
        [31, "B.Cu", "signal"],
        [32, "B.Adhes", "user", "B.Adhesive"],
        [33, "F.Adhes", "user", "F.Adhesive"],
        [34, "B.Paste", "user"],
        [35, "F.Paste", "user"],
        [36, "B.SilkS", "user", "B.Silkscreen"],
        [37, "F.SilkS", "user", "F.Silkscreen"],
        [38, "B.Mask", "user"],
        [39, "F.Mask", "user"],
        [40, "Dwgs.User", "user", "User.Drawings"],
        [41, "Cmts.User", "user", "User.Comments"],
        [42, "Eco1.User", "user", "User.Eco1"],
        [43, "Eco2.User", "user", "User.Eco2"],
        [44, "Edge.Cuts", "user"],
        [45, "Margin", "user"],
        [46, "B.CrtYd", "user", "B.Courtyard"],
        [47, "F.CrtYd", "user", "F.Courtyard"],
        [48, "B.Fab", "user"],
        [49, "F.Fab", "user"],
    ]


def _pin_header_fp(
    ref: str,
    value: str,
    net_names: tuple[str, ...] | list[str],
    x: float,
    y: float,
    *,
    pitch: float = 2.54,
) -> list:
    """Inline 1×N vertical pin header footprint (no external lib dependency)."""
    pads = []
    nets = []
    for i, net in enumerate(net_names):
        pad_n = i + 1
        net_id = i + 1
        nets.append(["net", net_id, net])
        py = y + i * pitch
        pads.append(
            [
                "pad",
                str(pad_n),
                "thru_hole",
                "circle",
                ["at", 0, i * pitch],
                ["size", 1.7, 1.7],
                ["drill", 1.0],
                ["layers", "*.Cu", "*.Mask"],
                ["net", net_id, net],
                ["pintype", "passive"],
                ["uuid", det_uuid(f"pad/{ref}/{pad_n}")],
            ]
        )
    n = len(net_names)
    height = max(pitch, (n - 1) * pitch) + 2.0
    fp = [
        "footprint",
        f"Connector_PinHeader_2.54mm:PinHeader_1x{n}_P2.54mm_Vertical",
        ["layer", "F.Cu"],
        ["uuid", det_uuid(f"fp/{ref}")],
        ["at", x, y],
        ["descr", f"Pin header {n}x1"],
        ["tags", "connector"],
        ["property", "Reference", ref, ["at", 0, -2.5, 0], ["layer", "F.SilkS"], ["uuid", det_uuid(f"fp/{ref}/ref")]],
        ["property", "Value", value, ["at", 0, height, 0], ["layer", "F.Fab"], ["uuid", det_uuid(f"fp/{ref}/val")]],
        ["property", "Footprint", "", ["at", 0, 0, 0], ["layer", "F.Fab"], ["hide", True], ["uuid", det_uuid(f"fp/{ref}/fp")]],
        ["property", "Datasheet", "", ["at", 0, 0, 0], ["layer", "F.Fab"], ["hide", True], ["uuid", det_uuid(f"fp/{ref}/ds")]],
        ["property", "Description", "", ["at", 0, 0, 0], ["layer", "F.Fab"], ["hide", True], ["uuid", det_uuid(f"fp/{ref}/desc")]],
        ["attr", "through_hole"],
        [
            "fp_line",
            ["start", -1.5, -1.5],
            ["end", 1.5, -1.5],
            ["stroke", ["width", 0.12], ["type", "solid"]],
            ["layer", "F.SilkS"],
            ["uuid", det_uuid(f"fp/{ref}/silk1")],
        ],
        [
            "fp_rect",
            ["start", -1.8, -1.8],
            ["end", 1.8, (n - 1) * pitch + 1.8],
            ["stroke", ["width", 0.05], ["type", "solid"]],
            ["fill", "none"],
            ["layer", "F.CrtYd"],
            ["uuid", det_uuid(f"fp/{ref}/crtyd")],
        ],
        *pads,
    ]
    return fp, nets


def _emit_pcb(
    out_dir: Path,
    name: str,
    width_mm: float,
    height_mm: float,
    connectors: list[tuple[str, str, tuple[str, ...] | list[str], float, float]],
) -> Path:
    """Fab-oriented PCB: outline + connectors. Each net on at most one pad (no autoroute)."""
    all_nets: dict[str, int] = {}
    net_list: list = [["net", 0, ""]]
    footprints: list = []
    seen: set[str] = set()

    next_id = 1
    pitch = 2.54
    for ref, value, pins, x, y in connectors:
        local_nets = []
        for p in pins:
            if p in seen:
                raise ValueError(
                    f"PCB {name}: net {p!r} repeated on {ref}; "
                    "keep one pad per net for DRC-clean connector boards"
                )
            seen.add(p)
            if p not in all_nets:
                all_nets[p] = next_id
                net_list.append(["net", next_id, p])
                next_id += 1
            local_nets.append(p)
        fp, _ = _pin_header_fp(ref, value, local_nets, x, y, pitch=pitch)
        for node in fp:
            if isinstance(node, list) and node and node[0] == "pad":
                for i, sub in enumerate(node):
                    if isinstance(sub, list) and sub and sub[0] == "net":
                        nname = sub[2]
                        node[i] = ["net", all_nets[nname], nname]
        footprints.append(fp)

    body: list = [
        "kicad_pcb",
        ["version", KICAD_PCB_VERSION],
        ["generator", "core-memory-redux"],
        ["generator_version", "10.0"],
        ["general", ["thickness", 1.6], ["legacy_teardrops", False]],
        ["paper", "A4"],
        _pcb_layers_2(),
        [
            "setup",
            ["pad_to_mask_clearance", 0],
            [
                "pcbplotparams",
                ["layerselection", "0x00010fc_ffffffff"],
                ["plot_on_all_layers_selection", "0x0000000_00000000"],
                ["disableapertmacros", False],
                ["usegerberextensions", False],
                ["usegerberattributes", True],
                ["usegerberadvancedattributes", True],
                ["creategerberjobfile", True],
                ["dashed_line_dash_ratio", 12],
                ["dashed_line_gap_ratio", 3],
                ["svgprecision", 4],
                ["plotframeref", False],
                ["mode", 1],
                ["useauxorigin", False],
                ["hpglpennumber", 1],
                ["hpglpenspeed", 20],
                ["hpglpendiameter", 15],
                ["pdf_front_fp_property_popups", True],
                ["pdf_back_fp_property_popups", True],
                ["dxfpolygonmode", True],
                ["dxfimperialunits", True],
                ["dxfusepcbnewfont", True],
                ["psnegative", False],
                ["psa4output", False],
                ["plotreference", True],
                ["plotvalue", True],
                ["plotfptext", True],
                ["plotinvisibletext", False],
                ["sketchpadsonfab", False],
                ["subtractmaskfromsilk", False],
                ["outputformat", 1],
                ["mirror", False],
                ["drillshape", 1],
                ["scaleselection", 1],
                ["outputdirectory", ""],
            ],
        ],
        *net_list,
        [
            "gr_rect",
            ["start", 0, 0],
            ["end", width_mm, height_mm],
            ["stroke", ["width", 0.1], ["type", "default"]],
            ["fill", "none"],
            ["layer", "Edge.Cuts"],
            ["uuid", det_uuid(f"edge/{name}")],
        ],
        [
            "gr_text",
            name,
            ["at", width_mm / 2, 5],
            ["layer", "F.SilkS"],
            ["uuid", det_uuid(f"silk/{name}")],
            ["effects", ["font", ["size", 2, 2], ["thickness", 0.3]]],
        ],
        *footprints,
    ]
    path = out_dir / f"{name}.kicad_pcb"
    write_sexpr(path, body)
    return path


def emit_ccs_sense_pcb(out_dir: Path) -> Path:
    """CCS + sense + power/bus host. One copper pad per net (fan-out on harness/sch)."""
    return _emit_pcb(
        out_dir,
        "pcb_ccs_sense",
        120.0,
        80.0,
        [
            ("J_BUS", "J_BUS", BUS_PINS, 10.0, 12.0),
            ("J_PLANE_SENSE", "J_PLANE_SENSE", PLANE_SENSE_PCB_PINS, 45.0, 12.0),
            ("J_PICO", "J_PICO", PICO_PCB_PINS, 70.0, 12.0),
            ("J_CCS_X", "CCS_X", ("CCS_X",), 10.0, 60.0),
            ("J_CCS_Y", "CCS_Y", ("CCS_Y",), 25.0, 60.0),
            ("J_CCS_INH", "CCS_INH", ("CCS_INH",), 40.0, 60.0),
        ],
    )


def emit_axis_octal_pcb(out_dir: Path) -> Path:
    return _emit_pcb(
        out_dir,
        "pcb_axis_octal",
        100.0,
        80.0,
        [
            ("J_BUS", "J_BUS", BUS_PINS, 10.0, 12.0),
            ("J_PLANE", "J_PLANE", PLANE_AB_PINS, 50.0, 12.0),
            ("JP_AXIS", "JP_AXIS", ("AXIS_X", "AXIS_Y"), 10.0, 60.0),
            ("JP_G", "JP_G", ("G0", "G1", "G2"), 30.0, 60.0),
        ],
    )


# --- Project entry points ---------------------------------------------------


def _clean_generated(out_dir: Path) -> None:
    if not out_dir.exists():
        return
    for pattern in ("*.kicad_sch", "*.kicad_pro", "*.kicad_pcb", "*_manifest.json", "README.md"):
        for p in out_dir.glob(pattern):
            p.unlink()


def emit_board(board: str, kicad_root: Path | None = None) -> Path:
    """board: 'ccs' | 'axis' | 'all'."""
    root = kicad_root or KICAD_ROOT
    board = board.lower()
    if board == "all":
        paths = [emit_board("ccs", root), emit_board("axis", root)]
        return paths[-1]  # CLI prints last; both written under root

    if board in ("ccs", "ccs_sense", "pcb_ccs_sense"):
        name = "pcb_ccs_sense"
        out = root / name
        _clean_generated(out)
        out.mkdir(parents=True, exist_ok=True)
        sch = emit_ccs_sense_sch(out)
        pcb = emit_ccs_sense_pcb(out)
        _emit_pro(out, name, "ccs_sense")
        manifest = {
            "board": name,
            "root_sch": sch.name,
            "pcb": pcb.name,
            "bus_pins": list(BUS_PINS),
            "sense_pins": list(PLANE_SENSE_PINS),
            "sense_pcb_pins": list(PLANE_SENSE_PCB_PINS),
            "pico_pins": list(PICO_PINS),
            "pico_pcb_pins": list(PICO_PCB_PINS),
            "ccs_trims": list(CCS_TRIM_REFS),
            "sense_nets": sorted(SENSE_NETS),
            "stackup": "2-layer fab prototype; 4-layer preferred",
            "role": "CCS + sense + power/bus distribution",
        }
        (out / "board_manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (out / "README.md").write_text(
            f"# {name} (GENERATED)\n\n"
            f"{BANNER_BOARD.format(board='ccs')}\n\n"
            f"- Schematic: `{sch.name}`\n"
            f"- PCB: `{pcb.name}`\n"
            f"- ICD: `docs/board_icd.md`\n",
            encoding="utf-8",
        )
        return out

    if board in ("axis", "axis_octal", "pcb_axis_octal"):
        name = "pcb_axis_octal"
        out = root / name
        _clean_generated(out)
        out.mkdir(parents=True, exist_ok=True)
        sch = emit_axis_octal_sch(out, group=0)
        pcb = emit_axis_octal_pcb(out)
        _emit_pro(out, name, "axis_octal")
        steer = axis_steer_pins(0)
        manifest = {
            "board": name,
            "root_sch": sch.name,
            "pcb": pcb.name,
            "bus_pins": list(BUS_PINS),
            "plane_ab_pins": list(PLANE_AB_PINS),
            "steer_pin_count": len(steer),
            "steer_pins": list(steer),
            "sense_nets_forbidden": sorted(SENSE_NETS),
            "group_bringup": 0,
            "stackup": "2-layer fab prototype; 4-layer preferred",
        }
        (out / "board_manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (out / "README.md").write_text(
            f"# {name} (GENERATED)\n\n"
            f"{BANNER_BOARD.format(board='axis')}\n\n"
            f"- Schematic: `{sch.name}`\n"
            f"- PCB: `{pcb.name}`\n"
            f"- Identical PCB for X and Y; strap JP_AXIS / JP_G\n"
            f"- ICD: `docs/board_icd.md`\n",
            encoding="utf-8",
        )
        return out

    raise ValueError(f"unknown board {board!r}; use ccs|axis|all")
