"""Emit multi-board KiCad projects: pcb_ccs_sense + pcb_axis_octal.

GENERATED trees — do not hand-edit; regenerate via:
  uv run python -m generators.cli --board ccs|axis
"""

from __future__ import annotations

import json
from pathlib import Path

from generators.abi import SENSE_NETS
from generators.board_abi import (
    AXIS_STEER_PIN_COUNT,
    BUS_PINS,
    CCS_TRIM_REFS,
    PICO_PCB_PINS,
    PICO_PINS,
    PLANE_AB_PINS,
    PLANE_SENSE_PINS,
    PLANE_SENSE_PCB_PINS,
    axis_steer_pins,
)
from generators.bom_parts import (
    CCS_CHANNELS,
    PART_74AHC74,
    PART_74AHC138,
    PART_74AHC238,
    PART_BAT54S,
    PART_IRLZ44N,
    PART_OPA192,
    PART_PICO,
    PART_R1K,
    PART_R10K,
    PART_RSENSE,
    PART_SS14,
    PART_TBD62083,
    PART_TBD62783,
    PART_TL431,
    PART_TLV3501,
    PART_TRIM,
)
from generators.emit_kicad import (
    KICAD_ROOT,
    _global_label,
    _global_label_terminated,
    _lib_diode,
    _lib_r,
    _lib_stub,
    _place_diode,
    _place_r,
    _place_stub,
    _sheet_base,
    _text,
    _wire,
    snap,
)
from generators.mce_array import build_fabric
from generators.place_lib import load_board_footprint, place_part_nc
from generators.sexpr import det_uuid, parse_sexpr, write_sexpr

BANNER_BOARD = (
    "GENERATED by generators/ — do not hand-edit; "
    "uv run python -m generators.cli --board {board}"
)

PINHEADER_PRETTY = Path(
    "/usr/share/kicad/footprints/Connector_PinHeader_2.54mm.pretty"
)


def _emit_pro(out_dir: Path, name: str, root_sheet: str) -> None:
    """Emit KiCad 10 JSON project; stem must match root .kicad_sch / .kicad_pcb."""
    root_uuid = det_uuid(f"sheet/{root_sheet}")
    pro = {
        "board": {
            "design_settings": {
                "defaults": {},
                "diff_pair_dimensions": [],
                "drc_exclusions": [],
                "rules": {},
                "track_widths": [],
                "via_dimensions": [],
            }
        },
        "boards": [],
        "libraries": {"pinned_footprint_libs": [], "pinned_symbol_libs": []},
        "meta": {"filename": f"{name}.kicad_pro", "version": 3},
        "net_settings": {"classes": [], "meta": {"version": 0}},
        "pcbnew": {"page_layout_descr_file": ""},
        "schematic": {
            "meta": {"version": 1},
            "page_layout_descr_file": "",
            "plot_directory": "",
        },
        "sheets": [[root_uuid, "Root"]],
        "text_variables": {},
    }
    (out_dir / f"{name}.kicad_pro").write_text(
        json.dumps(pro, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _root_port(name: str, x: float, y: float, sheet_uuid: str) -> list[list]:
    """Global-label connector stub (two stubs — avoids isolated_pin_label)."""
    x, y = snap(x), snap(y)
    rx = snap(x + 12.7)
    rx2 = snap(x + 15.24)
    ref = "TP_" + "".join(c if c.isalnum() else "_" for c in f"{name}_{x:g}_{y:g}")[:20]
    return [
        _global_label(name, x, y, 0),
        _wire(f"port/{name}@{x},{y}", x, y, rx, y),
        _place_stub(f"portStub/{name}@{x},{y}", ref, rx, y, sheet_uuid),
        _wire(f"porth/{name}@{x},{y}", rx, y, rx2, y),
        _place_stub(f"portStub2/{name}@{x},{y}", ref + "b", rx2, y, sheet_uuid),
    ]


def _connector_ports(
    items: list,
    suuid: str,
    prefix: str,
    pins: tuple[str, ...] | list[str],
    x0: float,
    y0: float,
) -> None:
    del prefix  # reserved for future silkscreen grouping
    y = y0
    x = x0
    for pin in pins:
        items.extend(_root_port(pin, x, y, suuid))
        y += 2.54
        if y > 180:
            y = y0
            x += 40.0


# --- Schematics -------------------------------------------------------------


def emit_ccs_sense_sch(out_dir: Path) -> Path:
    # Stem must match .kicad_pro / .kicad_pcb (KiCad looks up <stem>.kicad_sch).
    key = "pcb_ccs_sense"
    body, suuid = _sheet_base(
        key,
        "pcb_ccs_sense — CCS×3 + sense/fold + Pico + bus host",
        8,
        [_lib_r(), _lib_stub()],
    )
    lib_cache: dict[str, list] = {}
    items: list = [
        _text(f"{key}/banner", BANNER_BOARD.format(board="ccs"), 10, 8),
        _text(
            f"{key}/tune",
            "Tune: RTRIM_X/Y/INH (3296W), VDRIVE, JP_INH_POL — design_choices",
            10,
            13,
        ),
        _text(f"{key}/fold", "YA66 ≡ YB65 ≡ SENSE_FOLD (local fold)", 10, 18),
        _text(
            f"{key}/bom",
            "BOM: TL431+OPA192+IRLZ44N+1R + BAT54S+TLV3501+74AHC74 — component_selection §6.1",
            10,
            23,
        ),
    ]

    _connector_ports(items, suuid, "sense", PLANE_SENSE_PINS, 20.0, 30.0)
    _connector_ports(items, suuid, "bus", BUS_PINS, 20.0, 55.0)
    _connector_ports(items, suuid, "pico", PICO_PINS, 70.0, 30.0)

    # CCS channels — one column each (ref / trim / opamp / MOSFET / Rsense)
    for i, ch in enumerate(CCS_CHANNELS):
        cx = 160.0 + i * 55.0
        place_part_nc(PART_TL431, f"U_REF_{ch}", cx, 45.0, suuid, lib_cache, items)
        place_part_nc(PART_TRIM, f"RTRIM_{ch}", cx, 70.0, suuid, lib_cache, items)
        place_part_nc(
            PART_OPA192, f"U_OA_{ch}", cx, 100.0, suuid, lib_cache, items, unit_dx=25.4
        )
        place_part_nc(PART_IRLZ44N, f"Q_CCS_{ch}", cx, 145.0, suuid, lib_cache, items)
        place_part_nc(
            PART_RSENSE, f"Rsense_{ch}", cx + 20.0, 145.0, suuid, lib_cache, items
        )
        items.extend(_global_label_terminated(f"CCS_{ch}", cx + 20.0, 155.0, suuid, 0))

    # Sense / write-back
    place_part_nc(PART_BAT54S, "D_CLAMP", 330.0, 45.0, suuid, lib_cache, items)
    place_part_nc(PART_TLV3501, "U_COMP", 330.0, 75.0, suuid, lib_cache, items)
    place_part_nc(
        PART_74AHC74, "U_LATCH", 330.0, 110.0, suuid, lib_cache, items, unit_dx=25.4
    )
    place_part_nc(PART_R1K, "Riso_A", 370.0, 45.0, suuid, lib_cache, items)
    place_part_nc(PART_R1K, "Riso_B", 385.0, 45.0, suuid, lib_cache, items)
    place_part_nc(PART_R10K, "Rfold", 370.0, 70.0, suuid, lib_cache, items)
    items.extend(_global_label_terminated("SENSE_FOLD", 370.0, 80.0, suuid, 0))
    place_part_nc(PART_PICO, "J_PICO_HDR", 330.0, 165.0, suuid, lib_cache, items)

    # Inject embedded stock symbols into lib_symbols (index 6 in _sheet_base)
    lib_node = next(n for n in body if isinstance(n, list) and n and n[0] == "lib_symbols")
    for sym in lib_cache.values():
        lib_node.append(sym)

    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    path = out_dir / f"{key}.kicad_sch"
    write_sexpr(path, body)
    return path


def emit_axis_octal_sch(out_dir: Path, group: int = 0) -> Path:
    fabric = build_fabric(64)
    tile = next(t for t in fabric.tiles if t.axis == "X" and t.group == group)

    # Stem must match .kicad_pro / .kicad_pcb (KiCad looks up <stem>.kicad_sch).
    key = "pcb_axis_octal"
    body, suuid = _sheet_base(
        key,
        f"pcb_axis_octal — decode+DMOS+SS14 group g={group} (X/Y identical PCB)",
        8,
        [_lib_diode(), _lib_r(), _lib_stub()],
    )
    lib_cache: dict[str, list] = {}
    items: list = [
        _text(f"{key}/banner", BANNER_BOARD.format(board="axis"), 10, 8),
        _text(
            f"{key}/id",
            "JP_AXIS=X|Y  JP_G[2:0]=group  bring-up: g=0",
            10,
            13,
        ),
        _text(
            f"{key}/pins",
            f"REQ-HIER-OCTAL steer pins={AXIS_STEER_PIN_COUNT} lines={list(tile.lines)}",
            10,
            18,
        ),
        _text(
            f"{key}/mpn",
            "Decode 74AHC138+74AHC238; DMOS TBD62783/TBD62083; steer SS14",
            10,
            23,
        ),
    ]

    steer_pins = axis_steer_pins(group)
    assert len(steer_pins) == AXIS_STEER_PIN_COUNT
    _connector_ports(items, suuid, "steer", list(steer_pins), 20.0, 35.0)
    _connector_ports(items, suuid, "bus", BUS_PINS, 100.0, 35.0)
    _connector_ports(items, suuid, "plane", PLANE_AB_PINS, 180.0, 35.0)

    # Decode + DMOS (FWD/REV × HS/LS)
    place_part_nc(PART_74AHC138, "U_HS_FWD", 260.0, 40.0, suuid, lib_cache, items)
    place_part_nc(PART_74AHC138, "U_HS_REV", 300.0, 40.0, suuid, lib_cache, items)
    place_part_nc(PART_74AHC238, "U_LS_FWD", 260.0, 90.0, suuid, lib_cache, items)
    place_part_nc(PART_74AHC238, "U_LS_REV", 300.0, 90.0, suuid, lib_cache, items)
    place_part_nc(PART_TBD62783, "U_DMOS_HS_FWD", 340.0, 40.0, suuid, lib_cache, items)
    place_part_nc(PART_TBD62783, "U_DMOS_HS_REV", 380.0, 40.0, suuid, lib_cache, items)
    place_part_nc(PART_TBD62083, "U_DMOS_LS_FWD", 340.0, 90.0, suuid, lib_cache, items)
    place_part_nc(PART_TBD62083, "U_DMOS_LS_REV", 380.0, 90.0, suuid, lib_cache, items)

    # Fail-safe resistors (also place stock Device:R for footprint on PCB)
    place_part_nc(PART_R10K, "Rpu_FWD", 260.0, 140.0, suuid, lib_cache, items)
    place_part_nc(PART_R10K, "Rpu_REV", 280.0, 140.0, suuid, lib_cache, items)
    place_part_nc(PART_R10K, "Rpd_DEC", 300.0, 140.0, suuid, lib_cache, items)
    items.extend(_global_label_terminated("FWD_EN_n", 260.0, 150.0, suuid, 0))
    items.extend(_global_label_terminated("REV_EN_n", 280.0, 150.0, suuid, 0))
    items.extend(_global_label_terminated("DEC_EN", 300.0, 150.0, suuid, 0))

    # SS14 steer array (CMR diode + labels — topology SSOT)
    dx, dy = 260.0, 165.0
    for i, edge in enumerate(tile.diodes):
        ref = f"D{group}_{i}"
        items.append(_place_diode(f"{key}/{ref}", ref, dx, dy, suuid))
        items.extend(_global_label_terminated(edge.anode, dx + 5.08, dy, suuid, 0))
        items.extend(_global_label_terminated(edge.cathode, dx - 5.08, dy, suuid, 180))
        items.append(_wire(f"{key}/{ref}/a", dx + 3.81, dy, dx + 5.08, dy))
        items.append(_wire(f"{key}/{ref}/k", dx - 3.81, dy, dx - 5.08, dy))
        dy += 7.62
        if dy > 260:
            dy = 165.0
            dx += 35.0

    lib_node = next(n for n in body if isinstance(n, list) and n and n[0] == "lib_symbols")
    for sym in lib_cache.values():
        lib_node.append(sym)

    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    path = out_dir / f"{key}.kicad_sch"
    write_sexpr(path, body)
    return path


# --- PCB layouts ------------------------------------------------------------

KICAD_PCB_VERSION = 20241229


def _pcb_layers_2() -> list:
    return [
        "layers",
        [0, "F.Cu", "signal"],
        [31, "B.Cu", "signal"],
        [32, "B.Adhes", "user", "B.Adhesive"],
        [33, "F.Adhes", "user", "F.Adhesive"],
        [34, "B.Paste", "user"],
        [35, "F.Paste", "user"],
        [36, "B.SilkS", "user", "B.Silkscreen"],
        [37, "F.SilkS", "user", "F.Silkscreen"],
        [38, "B.Mask", "user"],
        [39, "F.Mask", "user"],
        [40, "Dwgs.User", "user", "User.Drawings"],
        [41, "Cmts.User", "user", "User.Comments"],
        [42, "Eco1.User", "user", "User.Eco1"],
        [43, "Eco2.User", "user", "User.Eco2"],
        [44, "Edge.Cuts", "user"],
        [45, "Margin", "user"],
        [46, "B.CrtYd", "user", "B.Courtyard"],
        [47, "F.CrtYd", "user", "F.Courtyard"],
        [48, "B.Fab", "user"],
        [49, "F.Fab", "user"],
    ]


def _pin_header_fp(
    ref: str,
    value: str,
    net_names: tuple[str, ...] | list[str],
    x: float,
    y: float,
    *,
    pitch: float = 2.54,
) -> list:
    """Load official KiCad pin-header footprint and bind nets (DRC-clean)."""
    del pitch
    n = len(net_names)
    mod_name = f"PinHeader_1x{n:02d}_P2.54mm_Vertical"
    lib_id = f"Connector_PinHeader_2.54mm:{mod_name}"
    path = PINHEADER_PRETTY / f"{mod_name}.kicad_mod"
    if not path.is_file():
        raise FileNotFoundError(path)
    tree = parse_sexpr(path.read_text(encoding="utf-8"))
    if not isinstance(tree, list) or tree[0] != "footprint":
        raise ValueError(f"bad footprint file {path}")

    # Clone and rewrite as a board footprint instance.
    fp: list = ["footprint", lib_id]
    skip_heads = {
        "version",
        "generator",
        "generator_version",
        "layer",  # re-added below
        "tedit",
        "uuid",
        "at",
    }
    body_nodes = []
    for node in tree[2:]:
        if isinstance(node, list) and node and node[0] in skip_heads:
            continue
        body_nodes.append(node)

    fp.extend(
        [
            ["layer", "F.Cu"],
            ["uuid", det_uuid(f"fp/{ref}")],
            ["at", x, y],
            [
                "property",
                "Reference",
                ref,
                ["at", 0, -2.5, 0],
                ["layer", "F.SilkS"],
                ["uuid", det_uuid(f"fp/{ref}/prop/Reference")],
            ],
            [
                "property",
                "Value",
                value,
                ["at", 0, 2.5, 0],
                ["layer", "F.Fab"],
                ["uuid", det_uuid(f"fp/{ref}/prop/Value")],
            ],
            [
                "property",
                "Footprint",
                lib_id,
                ["at", 0, 0, 0],
                ["layer", "F.Fab"],
                ["hide", True],
                ["uuid", det_uuid(f"fp/{ref}/prop/Footprint")],
            ],
        ]
    )

    pad_i = 0
    for node in body_nodes:
        if isinstance(node, list) and node and node[0] == "pad":
            pad_i += 1
            net_name = net_names[pad_i - 1]
            new_pad = [x for x in node if not (isinstance(x, list) and x and x[0] in ("uuid", "net"))]
            new_pad.append(["net", pad_i, net_name])  # net id patched later
            new_pad.append(["uuid", det_uuid(f"pad/{ref}/{pad_i}")])
            fp.append(new_pad)
        elif isinstance(node, list) and node and node[0] == "fp_text":
            # Library uses bare reference/value; set instance texts.
            txt = list(node)
            if len(txt) >= 3 and txt[1] == "reference":
                txt[2] = ref
            elif len(txt) >= 3 and txt[1] == "value":
                txt[2] = value
            # restamp tstamp/uuid children if present
            cleaned = []
            for part in txt:
                if isinstance(part, list) and part and part[0] in ("tstamp", "uuid"):
                    continue
                cleaned.append(part)
            kind = cleaned[1] if len(cleaned) > 1 else "x"
            cleaned.append(["uuid", det_uuid(f"fp/{ref}/fp_text/{kind}")])
            fp.append(cleaned)
        elif isinstance(node, list) and node and node[0] == "property":
            prop = list(node)
            pname = prop[1] if len(prop) > 1 else ""
            prop = [p for p in prop if not (isinstance(p, list) and p and p[0] == "uuid")]
            if pname == "Reference":
                prop[2] = ref
            elif pname == "Value":
                prop[2] = value
            elif pname == "Footprint":
                prop[2] = lib_id
            prop.append(["uuid", det_uuid(f"fp/{ref}/prop/{pname}")])
            fp.append(prop)
        else:
            fp.append(node)

    nets = [["net", i + 1, net_names[i]] for i in range(n)]
    return fp, nets



def _emit_pcb(
    out_dir: Path,
    name: str,
    width_mm: float,
    height_mm: float,
    connectors: list[tuple[str, str, tuple[str, ...] | list[str], float, float]],
    bom_fps: list[tuple[str, str, str, float, float]],
) -> Path:
    """Fab-oriented PCB: outline + headers (netted) + BOM footprints (no nets yet)."""
    all_nets: dict[str, int] = {}
    net_list: list = [["net", 0, ""]]
    footprints: list = []
    seen: set[str] = set()

    next_id = 1
    for ref, value, pins, x, y in connectors:
        local_nets = []
        for p in pins:
            if p in seen:
                raise ValueError(
                    f"PCB {name}: net {p!r} repeated on {ref}; "
                    "keep one pad per net for DRC-clean connector boards"
                )
            seen.add(p)
            if p not in all_nets:
                all_nets[p] = next_id
                net_list.append(["net", next_id, p])
                next_id += 1
            local_nets.append(p)
        fp, _ = _pin_header_fp(ref, value, local_nets, x, y)
        for node in fp:
            if isinstance(node, list) and node and node[0] == "pad":
                for i, sub in enumerate(node):
                    if isinstance(sub, list) and sub and sub[0] == "net":
                        nname = sub[2]
                        node[i] = ["net", all_nets[nname], nname]
        footprints.append(fp)

    for ref, value, fp_id, x, y in bom_fps:
        footprints.append(load_board_footprint(fp_id, ref, value, x, y))

    body: list = [
        "kicad_pcb",
        ["version", KICAD_PCB_VERSION],
        ["generator", "core-memory-redux"],
        ["generator_version", "10.0"],
        ["general", ["thickness", 1.6], ["legacy_teardrops", False]],
        ["paper", "A4"],
        _pcb_layers_2(),
        [
            "setup",
            ["pad_to_mask_clearance", 0],
        ],
        *net_list,
        [
            "gr_rect",
            ["start", 0, 0],
            ["end", width_mm, height_mm],
            ["stroke", ["width", 0.1], ["type", "default"]],
            ["fill", "none"],
            ["layer", "Edge.Cuts"],
            ["uuid", det_uuid(f"edge/{name}")],
        ],
        [
            "gr_text",
            name,
            ["at", width_mm / 2, 5],
            ["layer", "F.SilkS"],
            ["uuid", det_uuid(f"silk/{name}")],
            ["effects", ["font", ["size", 2, 2], ["thickness", 0.3]]],
        ],
        *footprints,
    ]
    path = out_dir / f"{name}.kicad_pcb"
    write_sexpr(path, body)
    return path


def emit_ccs_sense_pcb(out_dir: Path) -> Path:
    """CCS + sense + power/bus host. Headers netted; BOM footprints placed."""
    bom: list[tuple[str, str, str, float, float]] = []
    # CCS channel strips (left→right)
    for i, ch in enumerate(CCS_CHANNELS):
        x0 = 15.0 + i * 35.0
        bom.append((f"U_REF_{ch}", PART_TL431.mpn, PART_TL431.footprint, x0, 45.0))
        bom.append((f"RTRIM_{ch}", PART_TRIM.mpn, PART_TRIM.footprint, x0 + 12.0, 45.0))
        bom.append((f"U_OA_{ch}", PART_OPA192.mpn, PART_OPA192.footprint, x0, 60.0))
        bom.append((f"Q_CCS_{ch}", PART_IRLZ44N.mpn, PART_IRLZ44N.footprint, x0, 78.0))
        bom.append(
            (f"Rsense_{ch}", PART_RSENSE.mpn, PART_RSENSE.footprint, x0 + 14.0, 78.0)
        )
    bom.extend(
        [
            ("D_CLAMP", PART_BAT54S.mpn, PART_BAT54S.footprint, 125.0, 45.0),
            ("U_COMP", PART_TLV3501.mpn, PART_TLV3501.footprint, 125.0, 55.0),
            ("U_LATCH", PART_74AHC74.mpn, PART_74AHC74.footprint, 125.0, 68.0),
            ("Riso_A", PART_R1K.mpn, PART_R1K.footprint, 140.0, 45.0),
            ("Riso_B", PART_R1K.mpn, PART_R1K.footprint, 145.0, 45.0),
            ("Rfold", PART_R10K.mpn, PART_R10K.footprint, 140.0, 55.0),
            ("J_PICO_HDR", PART_PICO.mpn, PART_PICO.footprint, 160.0, 30.0),
        ]
    )
    return _emit_pcb(
        out_dir,
        "pcb_ccs_sense",
        220.0,
        120.0,
        [
            ("J_BUS", "J_BUS", BUS_PINS, 10.0, 12.0),
            ("J_PLANE_SENSE", "J_PLANE_SENSE", PLANE_SENSE_PCB_PINS, 55.0, 12.0),
            ("J_PICO", "J_PICO", PICO_PCB_PINS, 80.0, 12.0),
            ("J_CCS_X", "CCS_X", ("CCS_X",), 10.0, 95.0),
            ("J_CCS_Y", "CCS_Y", ("CCS_Y",), 25.0, 95.0),
            ("J_CCS_INH", "CCS_INH", ("CCS_INH",), 40.0, 95.0),
        ],
        bom,
    )


def emit_axis_octal_pcb(out_dir: Path) -> Path:
    bom: list[tuple[str, str, str, float, float]] = [
        ("U_HS_FWD", PART_74AHC138.mpn, PART_74AHC138.footprint, 20.0, 45.0),
        ("U_HS_REV", PART_74AHC138.mpn, PART_74AHC138.footprint, 45.0, 45.0),
        ("U_LS_FWD", PART_74AHC238.mpn, PART_74AHC238.footprint, 70.0, 45.0),
        ("U_LS_REV", PART_74AHC238.mpn, PART_74AHC238.footprint, 95.0, 45.0),
        ("U_DMOS_HS_FWD", PART_TBD62783.mpn, PART_TBD62783.footprint, 20.0, 65.0),
        ("U_DMOS_HS_REV", PART_TBD62783.mpn, PART_TBD62783.footprint, 50.0, 65.0),
        ("U_DMOS_LS_FWD", PART_TBD62083.mpn, PART_TBD62083.footprint, 80.0, 65.0),
        ("U_DMOS_LS_REV", PART_TBD62083.mpn, PART_TBD62083.footprint, 110.0, 65.0),
        ("Rpu_FWD", PART_R10K.mpn, PART_R10K.footprint, 130.0, 45.0),
        ("Rpu_REV", PART_R10K.mpn, PART_R10K.footprint, 135.0, 45.0),
        ("Rpd_DEC", PART_R10K.mpn, PART_R10K.footprint, 140.0, 45.0),
    ]
    # 32× SS14 SMA grid
    for i in range(32):
        col, row = divmod(i, 8)
        bom.append(
            (
                f"D0_{i}",
                PART_SS14.mpn,
                PART_SS14.footprint,
                20.0 + col * 8.0,
                85.0 + row * 6.0,
            )
        )
    return _emit_pcb(
        out_dir,
        "pcb_axis_octal",
        160.0,
        140.0,
        [
            ("J_BUS", "J_BUS", BUS_PINS, 10.0, 12.0),
            ("J_PLANE", "J_PLANE", PLANE_AB_PINS, 60.0, 12.0),
            ("JP_AXIS", "JP_AXIS", ("AXIS_X", "AXIS_Y"), 110.0, 12.0),
            ("JP_G", "JP_G", ("G0", "G1", "G2"), 130.0, 12.0),
        ],
        bom,
    )


# --- Project entry points ---------------------------------------------------


def _clean_generated(out_dir: Path) -> None:
    if not out_dir.exists():
        return
    for pattern in ("*.kicad_sch", "*.kicad_pro", "*.kicad_pcb", "*_manifest.json", "README.md"):
        for p in out_dir.glob(pattern):
            p.unlink()


def emit_board(board: str, kicad_root: Path | None = None) -> Path:
    """board: 'ccs' | 'axis' | 'all'."""
    root = kicad_root or KICAD_ROOT
    board = board.lower()
    if board == "all":
        paths = [emit_board("ccs", root), emit_board("axis", root)]
        return paths[-1]

    if board in ("ccs", "ccs_sense", "pcb_ccs_sense"):
        name = "pcb_ccs_sense"
        out = root / name
        _clean_generated(out)
        out.mkdir(parents=True, exist_ok=True)
        sch = emit_ccs_sense_sch(out)
        pcb = emit_ccs_sense_pcb(out)
        _emit_pro(out, name, name)
        manifest = {
            "board": name,
            "root_sch": sch.name,
            "pcb": pcb.name,
            "bus_pins": list(BUS_PINS),
            "sense_pins": list(PLANE_SENSE_PINS),
            "sense_pcb_pins": list(PLANE_SENSE_PCB_PINS),
            "pico_pins": list(PICO_PINS),
            "pico_pcb_pins": list(PICO_PCB_PINS),
            "ccs_trims": list(CCS_TRIM_REFS),
            "sense_nets": sorted(SENSE_NETS),
            "stackup": "2-layer fab prototype; 4-layer preferred",
            "role": "CCS + sense + power/bus distribution",
        }
        (out / "board_manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (out / "README.md").write_text(
            f"# {name} (GENERATED)\n\n"
            f"{BANNER_BOARD.format(board='ccs')}\n\n"
            f"- Schematic: `{sch.name}`\n"
            f"- PCB: `{pcb.name}`\n"
            f"- ICD: `docs/board_icd.md`\n",
            encoding="utf-8",
        )
        return out

    if board in ("axis", "axis_octal", "pcb_axis_octal"):
        name = "pcb_axis_octal"
        out = root / name
        _clean_generated(out)
        out.mkdir(parents=True, exist_ok=True)
        sch = emit_axis_octal_sch(out, group=0)
        pcb = emit_axis_octal_pcb(out)
        _emit_pro(out, name, name)
        steer = axis_steer_pins(0)
        manifest = {
            "board": name,
            "root_sch": sch.name,
            "pcb": pcb.name,
            "bus_pins": list(BUS_PINS),
            "plane_ab_pins": list(PLANE_AB_PINS),
            "steer_pin_count": len(steer),
            "steer_pins": list(steer),
            "sense_nets_forbidden": sorted(SENSE_NETS),
            "group_bringup": 0,
            "stackup": "2-layer fab prototype; 4-layer preferred",
        }
        (out / "board_manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (out / "README.md").write_text(
            f"# {name} (GENERATED)\n\n"
            f"{BANNER_BOARD.format(board='axis')}\n\n"
            f"- Schematic: `{sch.name}`\n"
            f"- PCB: `{pcb.name}`\n"
            f"- Identical PCB for X and Y; strap JP_AXIS / JP_G\n"
            f"- ICD: `docs/board_icd.md`\n",
            encoding="utf-8",
        )
        return out

    raise ValueError(f"unknown board {board!r}; use ccs|axis|all")
