"""Emit KiCad 10 hierarchical projects from FabricAST (GATE-L4-FABRIC).

GENERATED trees under kicad/{bringup_2x2,driver_64x64}/ — do not hand-edit;
fix topology in generators/ and re-run the CLI.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from generators.mce_array import FabricAST, OctalTile, build_fabric
from generators.sexpr import KICAD_SCH_VERSION, det_uuid, write_sexpr

ROOT = Path(__file__).resolve().parents[1]
KICAD_ROOT = ROOT / "kicad"

GENERATED_BANNER = (
    "GENERATED by generators/ — do not hand-edit; "
    "uv run python -m generators.cli --n {n}"
)

# KiCad schematic connection grid (50 mil).
GRID_MM = 1.27


def snap(v: float) -> float:
    """Snap to the schematic connection grid (avoids endpoint_off_grid)."""
    return round(v / GRID_MM) * GRID_MM


def _effects(size: float = 1.27, hide: bool = False, justify: str | None = None) -> list:
    eff: list = ["effects", ["font", ["size", size, size]]]
    if justify:
        eff.append(["justify", justify])
    if hide:
        eff.append(["hide", True])
    return eff


def _property(name: str, value: str, x: float, y: float, *, hide: bool = False) -> list:
    return [
        "property",
        name,
        value,
        ["at", x, y, 0],
        _effects(hide=hide),
    ]


def _lib_r() -> list:
    """Embedded resistor — CMR: prefix avoids Device library mismatch warnings."""
    return [
        "symbol",
        "CMR:R",
        ["pin_numbers", ["hide", True]],
        ["pin_names", ["offset", 0]],
        ["exclude_from_sim", False],
        ["in_bom", True],
        ["on_board", True],
        _property("Reference", "R", 2.032, 0),
        _property("Value", "R", 0, 0),
        _property("Footprint", "", -1.778, 0, hide=True),
        _property("Datasheet", "~", 0, 0, hide=True),
        _property("Description", "Resistor", 0, 0, hide=True),
        [
            "symbol",
            "R_0_1",
            [
                "rectangle",
                ["start", -1.016, -2.54],
                ["end", 1.016, 2.54],
                ["stroke", ["width", 0.254], ["type", "default"]],
                ["fill", ["type", "none"]],
            ],
        ],
        [
            "symbol",
            "R_1_1",
            [
                "pin",
                "passive",
                "line",
                ["at", 0, 3.81, 270],
                ["length", 1.27],
                ["name", "~", _effects()],
                ["number", "1", _effects()],
            ],
            [
                "pin",
                "passive",
                "line",
                ["at", 0, -3.81, 90],
                ["length", 1.27],
                ["name", "~", _effects()],
                ["number", "2", _effects()],
            ],
        ],
    ]


def _lib_stub() -> list:
    """One-pin passive stub — terminates labels/ports without NC-on-connected-pin."""
    return [
        "symbol",
        "CMR:Stub",
        ["pin_numbers", ["hide", True]],
        ["pin_names", ["offset", 0], ["hide", True]],
        ["exclude_from_sim", True],
        ["in_bom", False],
        ["on_board", False],
        _property("Reference", "TP", 1.27, 0),
        _property("Value", "Stub", 0, 0),
        _property("Footprint", "", 0, 0, hide=True),
        _property("Datasheet", "~", 0, 0, hide=True),
        _property("Description", "ERC stub terminator", 0, 0, hide=True),
        [
            "symbol",
            "Stub_0_1",
            [
                "circle",
                ["center", 0, 0],
                ["radius", 0.635],
                ["stroke", ["width", 0.254], ["type", "default"]],
                ["fill", ["type", "none"]],
            ],
        ],
        [
            "symbol",
            "Stub_1_1",
            [
                "pin",
                "passive",
                "line",
                ["at", -2.54, 0, 0],
                ["length", 2.54],
                ["name", "~", _effects()],
                ["number", "1", _effects()],
            ],
        ],
    ]


def _lib_diode() -> list:
    return [
        "symbol",
        "CMR:D_Schottky",
        ["pin_numbers", ["hide", True]],
        ["pin_names", ["offset", 1.016], ["hide", True]],
        ["exclude_from_sim", False],
        ["in_bom", True],
        ["on_board", True],
        _property("Reference", "D", 0, 0),
        _property("Value", "D_Schottky", 0, 0),
        _property("Footprint", "", 0, 0, hide=True),
        _property("Datasheet", "~", 0, 0, hide=True),
        _property("Description", "Schottky diode", 0, 0, hide=True),
        [
            "symbol",
            "D_Schottky_0_1",
            [
                "polyline",
                ["pts", ["xy", -1.27, 1.27], ["xy", -1.27, -1.27]],
                ["stroke", ["width", 0.254], ["type", "default"]],
                ["fill", ["type", "none"]],
            ],
            [
                "polyline",
                ["pts", ["xy", 1.27, 1.27], ["xy", 1.27, 0], ["xy", -1.27, 0], ["xy", 1.27, -1.27], ["xy", 1.27, 1.27]],
                ["stroke", ["width", 0.254], ["type", "default"]],
                ["fill", ["type", "none"]],
            ],
        ],
        [
            "symbol",
            "D_Schottky_1_1",
            [
                "pin",
                "passive",
                "line",
                ["at", -3.81, 0, 0],
                ["length", 2.54],
                ["name", "K", _effects()],
                ["number", "1", _effects()],
            ],
            [
                "pin",
                "passive",
                "line",
                ["at", 3.81, 0, 180],
                ["length", 2.54],
                ["name", "A", _effects()],
                ["number", "2", _effects()],
            ],
        ],
    ]


def _text(key: str, body: str, x: float, y: float) -> list:
    x, y = snap(x), snap(y)
    return [
        "text",
        body,
        ["exclude_from_sim", False],
        ["at", x, y, 0],
        _effects(1.0),
        ["uuid", det_uuid(f"text/{key}")],
    ]


def _global_label(name: str, x: float, y: float, angle: int = 0) -> list:
    x, y = snap(x), snap(y)
    return [
        "global_label",
        name,
        ["shape", "bidirectional"],
        ["at", x, y, angle],
        _effects(justify="left"),
        ["uuid", det_uuid(f"glab/{name}@{x},{y}")],
    ]


def _global_label_terminated(
    name: str, x: float, y: float, sheet_uuid: str, angle: int = 0
) -> list[list]:
    """Global label plus dual stubs so ERC does not flag isolated_pin_label."""
    x, y = snap(x), snap(y)
    # Offset stubs away from the component pin along +X.
    rx = snap(x + 5.08)
    rx2 = snap(x + 7.62)
    ref = "TP_" + re.sub(r"[^A-Za-z0-9]", "_", f"{name}_{x:g}_{y:g}")[:18]
    return [
        _global_label(name, x, y, angle),
        _wire(f"glabw/{name}@{x},{y}", x, y, rx, y),
        _place_stub(f"glabStub/{name}@{x},{y}", ref, rx, y, sheet_uuid),
        _wire(f"glabw2/{name}@{x},{y}", rx, y, rx2, y),
        _place_stub(f"glabStub2/{name}@{x},{y}", ref + "b", rx2, y, sheet_uuid),
    ]


def _hier_label(name: str, x: float, y: float, shape: str = "bidirectional") -> list:
    x, y = snap(x), snap(y)
    return [
        "hierarchical_label",
        name,
        ["shape", shape],
        ["at", x, y, 0],
        _effects(justify="left"),
        ["uuid", det_uuid(f"hlab/{name}@{x},{y}")],
    ]


def _wire(key: str, x1: float, y1: float, x2: float, y2: float) -> list:
    x1, y1, x2, y2 = snap(x1), snap(y1), snap(x2), snap(y2)
    return [
        "wire",
        ["pts", ["xy", x1, y1], ["xy", x2, y2]],
        ["stroke", ["width", 0], ["type", "default"]],
        ["uuid", det_uuid(f"wire/{key}")],
    ]


def _no_connect(key: str, x: float, y: float) -> list:
    x, y = snap(x), snap(y)
    return [
        "no_connect",
        ["at", x, y],
        ["uuid", det_uuid(f"nc/{key}")],
    ]


def _place_stub(key: str, ref: str, x: float, y: float, sheet_uuid: str) -> list:
    """Place one-pin CMR:Stub; pin hotspot is at (x, y) (pin approaches from the left)."""
    x, y = snap(x), snap(y)
    # Symbol origin is 2.54 mm right of the pin tip.
    at_x = snap(x + 2.54)
    return [
        "symbol",
        ["lib_id", "CMR:Stub"],
        ["at", at_x, y, 0],
        ["unit", 1],
        ["exclude_from_sim", True],
        ["in_bom", False],
        ["on_board", False],
        ["dnp", True],
        ["uuid", det_uuid(f"sym/{key}")],
        _property("Reference", ref, at_x + 1.27, y - 1.27, hide=True),
        _property("Value", "Stub", at_x + 1.27, y + 1.27, hide=True),
        _property("Footprint", "", at_x, y, hide=True),
        _property("Datasheet", "~", at_x, y, hide=True),
        ["pin", "1", ["uuid", det_uuid(f"pin/{key}/1")]],
        [
            "instances",
            [
                "project",
                "",
                [
                    "path",
                    f"/{sheet_uuid}",
                    ["reference", ref],
                    ["unit", 1],
                ],
            ],
        ],
    ]


def _hier_port(name: str, x: float, y: float, sheet_uuid: str, shape: str = "bidirectional") -> list[list]:
    """Hierarchical label terminated on two stubs (avoids isolated_pin_label)."""
    x, y = snap(x), snap(y)
    rx = snap(x + 12.7)
    rx2 = snap(x + 15.24)
    ref = "TP_" + re.sub(r"[^A-Za-z0-9]", "_", name)[:18]
    return [
        _hier_label(name, x, y, shape),
        _wire(f"port/{name}@{x},{y}", x, y, rx, y),
        _place_stub(f"portStub/{name}@{x},{y}", ref, rx, y, sheet_uuid),
        _wire(f"porth/{name}@{x},{y}", rx, y, rx2, y),
        _place_stub(f"portStub2/{name}@{x},{y}", ref + "b", rx2, y, sheet_uuid),
    ]


def _sheet_pin_nc(key: str, x: float, y: float, sheet_uuid: str) -> list[list]:
    """Wire a root hierarchical sheet pin out to a stub terminator."""
    x, y = snap(x), snap(y)
    x2 = snap(x - 12.7)
    ref = "TP_" + re.sub(r"[^A-Za-z0-9]", "_", key)[:20]
    return [
        _wire(f"spnc/{key}", x, y, x2, y),
        _place_stub(f"spStub/{key}", ref, x2, y, sheet_uuid),
    ]


def _place_r(
    key: str,
    ref: str,
    value: str,
    x: float,
    y: float,
    sheet_uuid: str,
) -> list:
    x, y = snap(x), snap(y)
    return [
        "symbol",
        ["lib_id", "CMR:R"],
        ["at", x, y, 0],
        ["unit", 1],
        ["exclude_from_sim", False],
        ["in_bom", True],
        ["on_board", True],
        ["dnp", False],
        ["uuid", det_uuid(f"sym/{key}")],
        _property("Reference", ref, x + 2.54, y - 1.27),
        _property("Value", value, x + 2.54, y + 1.27),
        _property("Footprint", "", x, y, hide=True),
        _property("Datasheet", "~", x, y, hide=True),
        ["pin", "1", ["uuid", det_uuid(f"pin/{key}/1")]],
        ["pin", "2", ["uuid", det_uuid(f"pin/{key}/2")]],
        [
            "instances",
            [
                "project",
                "",
                [
                    "path",
                    f"/{sheet_uuid}",
                    ["reference", ref],
                    ["unit", 1],
                ],
            ],
        ],
    ]


def _place_diode(
    key: str,
    ref: str,
    x: float,
    y: float,
    sheet_uuid: str,
) -> list:
    x, y = snap(x), snap(y)
    return [
        "symbol",
        ["lib_id", "CMR:D_Schottky"],
        ["at", x, y, 0],
        ["unit", 1],
        ["exclude_from_sim", False],
        ["in_bom", True],
        ["on_board", True],
        ["dnp", False],
        ["uuid", det_uuid(f"sym/{key}")],
        _property("Reference", ref, x, y - 2.54),
        _property("Value", "SS14", x, y + 2.54),
        _property("Footprint", "Diode_SMD:D_SMA", x, y, hide=True),
        _property("Datasheet", "~", x, y, hide=True),
        ["pin", "1", ["uuid", det_uuid(f"pin/{key}/1")]],
        ["pin", "2", ["uuid", det_uuid(f"pin/{key}/2")]],
        [
            "instances",
            [
                "project",
                "",
                [
                    "path",
                    f"/{sheet_uuid}",
                    ["reference", ref],
                    ["unit", 1],
                ],
            ],
        ],
    ]


def _sheet_base(key: str, title: str, n: int, lib_symbols: list | None = None) -> tuple[list, str]:
    suuid = det_uuid(f"sheet/{key}")
    body: list = [
        "kicad_sch",
        ["version", KICAD_SCH_VERSION],
        ["generator", "core-memory-redux"],
        ["generator_version", "10.0"],
        ["uuid", suuid],
        ["paper", "A3"],
        [
            "title_block",
            ["title", title],
            ["comment", 1, GENERATED_BANNER.format(n=n)],
        ],
        ["lib_symbols", *(lib_symbols or [])],
    ]
    return body, suuid


def emit_steer_tile(fabric: FabricAST, tile: OctalTile, out_dir: Path) -> str:
    """Emit one octal steer sheet with SS14 diodes for populated lines."""
    key = tile.sheet_name
    body, suuid = _sheet_base(key, key, fabric.n, [_lib_diode(), _lib_r(), _lib_stub()])
    items: list = [
        _text(f"{key}/banner", f"REQ-HIER-OCTAL {key} pins={len(tile.pins)}", 10, 10),
        _text(f"{key}/lines", f"lines={list(tile.lines)}", 10, 15),
    ]
    # Hierarchical pins along left edge
    y = 25.0
    for pin in tile.pins:
        items.extend(_hier_port(pin, 20.0, y, suuid))
        y += 2.54
        if y > 180:
            y = 25.0
    # Diodes: anode label — diode — cathode label
    dx, dy = 120.0, 25.0
    for i, edge in enumerate(tile.diodes):
        ref = f"D{tile.axis}{tile.group}_{i}"
        items.append(_place_diode(f"{key}/{ref}", ref, dx, dy, suuid))
        items.append(_global_label(edge.anode, dx + 5.08, dy, 0))
        items.append(_global_label(edge.cathode, dx - 5.08, dy, 180))
        items.append(_wire(f"{key}/{ref}/a", dx + 3.81, dy, dx + 5.08, dy))
        items.append(_wire(f"{key}/{ref}/k", dx - 3.81, dy, dx - 5.08, dy))
        dy += 7.62
        if dy > 180:
            dy = 25.0
            dx += 40.0
    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    path = out_dir / f"{key}.kicad_sch"
    write_sexpr(path, body)
    return key


def emit_decode_block(fabric: FabricAST, out_dir: Path) -> str:
    key = "decode_block"
    body, suuid = _sheet_base(
        key,
        "decode_block (74AHC138 HS + 74AHC238 LS)",
        fabric.n,
        [_lib_r(), _lib_stub()],
    )
    items: list = [
        _text(f"{key}/mpn", "MPN: 74AHC138 + 74AHC238 (lib_id 74xx; Value=AHC)", 10, 10),
        _text(f"{key}/failsafe", "Fail-safe: FWD_EN_n/REV_EN_n pull-up; DEC_EN pull-down", 10, 15),
    ]
    pins = [
        ("ADDR_NH0", "input"),
        ("ADDR_NH1", "input"),
        ("ADDR_NH2", "input"),
        ("ADDR_NL0", "input"),
        ("ADDR_NL1", "input"),
        ("ADDR_NL2", "input"),
        ("BANK_EN", "input"),
        ("DEC_EN", "input"),
    ]
    for i in range(8):
        pins.append((f"N_HS{i}_n", "output"))
    for i in range(8):
        pins.append((f"N_LS{i}_en", "output"))
    y = 25.0
    for name, shape in pins:
        items.extend(_hier_port(name, 25.0, y, suuid, shape))
        y += 2.54
    # Pull resistors on bank enables (tune/fail-safe presence)
    items.append(_place_r(f"{key}/Rpu", "Rpu_BANK", "10k", 100, 40, suuid))
    items.extend(_global_label_terminated("BANK_EN", 100, 40 - 3.81, suuid, 90))
    items.extend(_global_label_terminated("+3V3", 100, 40 + 3.81, suuid, 270))
    items.append(_place_r(f"{key}/Rpd", "Rpd_DEC", "10k", 120, 40, suuid))
    items.extend(_global_label_terminated("DEC_EN", 120, 40 - 3.81, suuid, 90))
    items.append(_global_label("AGND", 120, 40 + 3.81, 270))
    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    write_sexpr(out_dir / f"{key}.kicad_sch", body)
    return key


def emit_dmos(fabric: FabricAST, out_dir: Path, kind: str) -> str:
    """kind: hs -> TBD62783, ls -> TBD62083."""
    key = f"dmos_{kind}_array"
    mpn = "TBD62783" if kind == "hs" else "TBD62083"
    body, suuid = _sheet_base(key, f"{key} ({mpn})", fabric.n, [_lib_r(), _lib_stub()])
    items: list = [
        _text(f"{key}/mpn", f"REQ-DRV-DMOS MPN={mpn} — pin-faithful sheet; not transistor-level", 10, 10),
        *_hier_port("VDRIVE", 25, 25, suuid, "input"),
        *_hier_port("CCS_RET", 25, 30, suuid, "output"),
    ]
    y = 40.0
    for i in range(8):
        if kind == "hs":
            items.extend(_hier_port(f"IN{i}_n", 25, y, suuid, "input"))
            items.extend(_hier_port(f"OUT{i}", 80, y, suuid, "output"))
        else:
            items.extend(_hier_port(f"IN{i}_en", 25, y, suuid, "input"))
            items.extend(_hier_port(f"OUT{i}", 80, y, suuid, "output"))
        y += 2.54
    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    write_sexpr(out_dir / f"{key}.kicad_sch", body)
    return key


def emit_ccs(fabric: FabricAST, out_dir: Path) -> str:
    key = "ccs_channel"
    body, suuid = _sheet_base(
        key,
        "ccs_channel (TL431 + 3296W + OPA192 + IRLZ44N)",
        fabric.n,
        [_lib_r(), _lib_stub()],
    )
    items: list = [
        _text(f"{key}/tune", "Tune: multi-turn trimpot sets Ic/2 (200–400 mA band)", 10, 10),
        *_hier_port("CCS_RET", 25, 30, suuid, "input"),
        *_hier_port("ISENSE", 25, 35, suuid, "output"),
        *_hier_port("VDRIVE", 25, 40, suuid, "input"),
        _place_r(f"{key}/trim", "RTRIM", "3296W_10k", 80, 40, suuid),
        *_global_label_terminated("CCS_TRIM", 80, 40 - 3.81, suuid, 90),
        _global_label("AGND", 80, 40 + 3.81, 270),
    ]
    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    write_sexpr(out_dir / f"{key}.kicad_sch", body)
    return key


def emit_sense(fabric: FabricAST, out_dir: Path) -> str:
    key = "sense_front_end"
    body, suuid = _sheet_base(
        key,
        "sense_front_end (BAT54S + TLV3501 + 74AHC74 + INH_POL_SEL)",
        fabric.n,
        [_lib_r(), _lib_stub()],
    )
    items: list = [
        _text(f"{key}/pol", "INH_POL_SEL: default YA65 source / YB66 sink; jumper reverses", 10, 10),
        *_hier_port("YA65", 25, 30, suuid, "bidirectional"),
        *_hier_port("YB66", 25, 35, suuid, "bidirectional"),
        *_hier_port("DOUT", 25, 40, suuid, "output"),
        *_hier_port("SENSE_STROBE", 25, 45, suuid, "input"),
        *_hier_port("INH_POL_SEL", 25, 50, suuid, "input"),
        *_hier_port("PIO_STROBE", 25, 55, suuid, "input"),
        _place_r(f"{key}/iso", "Riso", "1k", 90, 40, suuid),
        _global_label("YA65", 90, 40 - 3.81, 90),
        *_global_label_terminated("SENSE_MID", 90, 40 + 3.81, suuid, 270),
    ]
    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    write_sexpr(out_dir / f"{key}.kicad_sch", body)
    return key


def emit_magnetic(fabric: FabricAST, out_dir: Path) -> str:
    key = "magnetic_plane"
    body, suuid = _sheet_base(
        key,
        f"magnetic_plane n={fabric.n} (bus/connector/fold interface)",
        fabric.n,
        [_lib_r(), _lib_stub()],
    )
    items: list = [
        _text(
            f"{key}/note",
            "Interface only — no 4096 core symbols. Weave proven by AST + L3 SIL.",
            10,
            10,
        ),
        _text(f"{key}/fold", "REQ-ICD-FOLD: YA66=YB65=SENSE_FOLD; 10k soft bias to AGND", 10, 15),
    ]
    y = 30.0
    for bus, nets in fabric.plane_buses.items():
        items.append(_text(f"{key}/bus/{bus}", f"{bus}[0..{fabric.n - 1}]", 20, y))
        # Expose endpoints + a few samples as hierarchical labels (full bus on root labels)
        for net in (nets[0], nets[-1]):
            items.extend(_hier_port(net, 40, y, suuid, "bidirectional"))
            y += 2.54
        y += 2.54
    for name in ("YA65", "YB66", "YA66", "YB65", "SENSE_FOLD"):
        items.extend(_hier_port(name, 40, y, suuid, "bidirectional"))
        y += 2.54
    # Soft bias + REQ-ICD-FOLD short: YA66 and YB65 share net SENSE_FOLD
    items.append(_place_r(f"{key}/Rfold", "Rfold", "10k", 120, 50, suuid))
    items.append(_global_label("SENSE_FOLD", 120, 50 - 3.81, 90))
    items.append(_global_label("AGND", 120, 50 + 3.81, 270))
    # Alias note only — do not place a second dangling SENSE_FOLD global.
    items.append(_text(f"{key}/alias", "YA66 ≡ YB65 ≡ SENSE_FOLD (external jumper)", 140, 40))
    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    write_sexpr(out_dir / f"{key}.kicad_sch", body)
    return key


def _sheet_instance(
    key: str,
    fname: str,
    x: float,
    y: float,
    w: float,
    pin_names: list[str],
) -> tuple[list, list]:
    """Hierarchical sheet box on root.

    Returns (sheet_node, tie_items) where tie_items wire each sheet pin to a
    same-named global label so ERC sees a connection.
    """
    x, y, w = snap(x), snap(y), snap(w)
    pins = []
    ties: list = []
    py = GRID_MM * 2
    for pn in pin_names:
        # KiCad: (pin "NAME" <electrical> (at x y rot) (uuid ...) (effects ...))
        pins.append(
            [
                "pin",
                pn,
                "bidirectional",
                ["at", x, y + py, 180],
                ["uuid", det_uuid(f"sheetpin/{key}/{pn}")],
                _effects(justify="left"),
            ]
        )
        ties.extend(_sheet_pin_nc(f"{key}/{pn}", x, y + py, det_uuid("sheet/driver")))
        py = snap(py + GRID_MM * 2)
    h = snap(max(25.4, py + GRID_MM * 2))
    sheet = [
        "sheet",
        ["at", x, y],
        ["size", w, h],
        ["exclude_from_sim", False],
        ["in_bom", True],
        ["on_board", True],
        ["dnp", False],
        ["fields_autoplaced", False],
        ["stroke", ["width", 0.1524], ["type", "solid"]],
        ["fill", ["type", "none"]],
        ["uuid", det_uuid(f"sheetbox/{key}")],
        [
            "property",
            "Sheetname",
            key,
            ["at", x, y - 1.27, 0],
            _effects(),
        ],
        [
            "property",
            "Sheetfile",
            fname,
            ["at", x, y + h + 1.27, 0],
            _effects(),
        ],
        *pins,
    ]
    return sheet, ties


def emit_root(fabric: FabricAST, out_dir: Path, sheet_files: dict[str, str]) -> None:
    key = "driver"
    body, _suuid = _sheet_base(
        key,
        f"{fabric.project_name()} root n={fabric.n}",
        fabric.n,
        [_lib_stub()],
    )
    items: list = [
        _text(
            f"{key}/tune",
            "Tune points: CCS_*_TRIM, VDRIVE, INH_POL_SEL, PIO_STROBE "
            "(design_choices bring-up; not ICD freeze)",
            10,
            8,
        ),
    ]

    # Pin lists must match hierarchical_label sets on child sheets (ERC hier match).
    magnetic_pins: list[str] = []
    for _bus, nets in fabric.plane_buses.items():
        magnetic_pins.extend((nets[0], nets[-1]))
    magnetic_pins.extend(["YA65", "YB66", "YA66", "YB65", "SENSE_FOLD"])

    decode_pins = [
        "ADDR_NH0",
        "ADDR_NH1",
        "ADDR_NH2",
        "ADDR_NL0",
        "ADDR_NL1",
        "ADDR_NL2",
        "BANK_EN",
        "DEC_EN",
        *[f"N_HS{i}_n" for i in range(8)],
        *[f"N_LS{i}_en" for i in range(8)],
    ]
    dmos_hs_pins = ["VDRIVE", "CCS_RET", *[f"IN{i}_n" for i in range(8)], *[f"OUT{i}" for i in range(8)]]
    dmos_ls_pins = ["VDRIVE", "CCS_RET", *[f"IN{i}_en" for i in range(8)], *[f"OUT{i}" for i in range(8)]]

    layout: list[tuple[str, str, list[str]]] = [
        ("magnetic_plane", sheet_files["magnetic_plane"], magnetic_pins),
        (
            "sense_front_end",
            sheet_files["sense_front_end"],
            ["YA65", "YB66", "DOUT", "SENSE_STROBE", "INH_POL_SEL", "PIO_STROBE"],
        ),
        ("ccs_channel", sheet_files["ccs_channel"], ["CCS_RET", "ISENSE", "VDRIVE"]),
        ("decode_block", sheet_files["decode_block"], decode_pins),
        ("dmos_hs_array", sheet_files["dmos_hs_array"], dmos_hs_pins),
        ("dmos_ls_array", sheet_files["dmos_ls_array"], dmos_ls_pins),
    ]

    x, y = snap(101.6), snap(25.4)
    for name, fname, pins in layout:
        sheet, ties = _sheet_instance(name, fname, x, y, snap(45.72), pins)
        items.append(sheet)
        items.extend(ties)
        x = snap(x + 55.88)
        if x > 355.6:
            x = snap(101.6)
            y = snap(y + 121.92)

    x, y = snap(101.6), snap(y + 129.54)
    for tile in fabric.tiles:
        fname = sheet_files[tile.sheet_name]
        sheet, ties = _sheet_instance(
            tile.sheet_name,
            fname,
            x,
            y,
            snap(40.64),
            list(tile.pins),
        )
        items.append(sheet)
        items.extend(ties)
        x = snap(x + 50.8)
        if x > 381.0:
            x = snap(101.6)
            y = snap(y + 111.76)

    dy = snap(y + 121.92)
    for call in fabric.decode_calls:
        items.append(
            _text(
                f"{key}/{call.instance}",
                f"{call.instance} -> decode_block.kicad_sch ({call.axis} {call.direction})",
                snap(101.6),
                dy,
            )
        )
        dy = snap(dy + 5.08)

    body.extend(items)
    body.append(["sheet_instances", ["path", "/", ["page", "1"]]])
    write_sexpr(out_dir / "driver.kicad_sch", body)



def emit_pro(fabric: FabricAST, out_dir: Path) -> None:
    """Minimal KiCad project file."""
    name = fabric.project_name()
    root_uuid = det_uuid("sheet/driver")
    pro = {
        "board": {
            "design_settings": {
                "defaults": {},
                "diff_pair_dimensions": [],
                "drc_exclusions": [],
                "rules": {},
                "track_widths": [],
                "via_dimensions": [],
            }
        },
        "boards": [],
        "libraries": {"pinned_footprint_libs": [], "pinned_symbol_libs": []},
        "meta": {"filename": f"{name}.kicad_pro", "version": 3},
        "net_settings": {"classes": [], "meta": {"version": 0}},
        "schematic": {
            "meta": {"version": 1},
            "page_layout_descr_file": "",
            "plot_directory": "",
        },
        "sheets": [[root_uuid, "Root"]],
        "text_variables": {},
    }
    (out_dir / f"{name}.kicad_pro").write_text(
        json.dumps(pro, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def emit_project(n: int, kicad_root: Path | None = None) -> Path:
    fabric = build_fabric(n)
    root = kicad_root or KICAD_ROOT
    out_dir = root / fabric.project_name()
    if out_dir.exists():
        # Idempotent clean of generated sch/pro/json only
        for p in out_dir.glob("*.kicad_sch"):
            p.unlink()
        for p in out_dir.glob("*.kicad_pro"):
            p.unlink()
        for p in out_dir.glob("fabric_manifest.json"):
            p.unlink()
    out_dir.mkdir(parents=True, exist_ok=True)

    sheet_files: dict[str, str] = {}
    for tile in fabric.tiles:
        name = emit_steer_tile(fabric, tile, out_dir)
        sheet_files[name] = f"{name}.kicad_sch"
    sheet_files["decode_block"] = f"{emit_decode_block(fabric, out_dir)}.kicad_sch"
    sheet_files["dmos_hs_array"] = f"{emit_dmos(fabric, out_dir, 'hs')}.kicad_sch"
    sheet_files["dmos_ls_array"] = f"{emit_dmos(fabric, out_dir, 'ls')}.kicad_sch"
    sheet_files["ccs_channel"] = f"{emit_ccs(fabric, out_dir)}.kicad_sch"
    sheet_files["sense_front_end"] = f"{emit_sense(fabric, out_dir)}.kicad_sch"
    sheet_files["magnetic_plane"] = f"{emit_magnetic(fabric, out_dir)}.kicad_sch"
    emit_root(fabric, out_dir, sheet_files)
    emit_pro(fabric, out_dir)

    manifest = fabric.summary()
    manifest["sheets"] = sorted(sheet_files.keys())
    manifest["root"] = "driver.kicad_sch"
    (out_dir / "fabric_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (out_dir / "README.md").write_text(
        f"# {fabric.project_name()} (GENERATED)\n\n"
        f"{GENERATED_BANNER.format(n=n)}\n\n"
        f"- Root: `driver.kicad_sch`\n"
        f"- Manifest: `fabric_manifest.json`\n"
        f"- Gate: **GATE-L4-FABRIC** / **REQ-HIER-OCTAL**\n",
        encoding="utf-8",
    )
    return out_dir
